const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5000/api"

export const API_ENDPOINTS = {
  LOGIN: `${API_URL}/auth/login`,
  VERIFY_TOKEN: `${API_URL}/auth/verify`,
  PROFILE: `${API_URL}/users/profile`,
  CHANGE_PASSWORD: `${API_URL}/users/change-password`,
  USERS: `${API_URL}/users`,
  CLIENTS: `${API_URL}/clients`,
  CLIENT_PROFILE: `${API_URL}/clients/my-profile`,
  CLIENT_CHANGE_PASSWORD: `${API_URL}/clients/my-profile/change-password`,
  NOTICES: `${API_URL}/notices`,
  CLASSES: `${API_URL}/classes`,
  PLANS: `${API_URL}/plans`,
  INSTRUCTORS: `${API_URL}/instructors`,
  MEMBERSHIPS: `${API_URL}/memberships`,
  CASH: `${API_URL}/cash`,
  CASH_ACTIVE: `${API_URL}/cash/active`,
  CASH_OPEN: `${API_URL}/cash/open`,
  CASH_CLOSE: `${API_URL}/cash/:id/close`,
  CASH_MOVEMENTS: `${API_URL}/cash/movements`,
  CASH_SESSIONS: `${API_URL}/cash/sessions`,
  CASH_SESSION_DETAIL: `${API_URL}/cash/sessions/:id`,
  CASH_INCOME_BREAKDOWN: `${API_URL}/cash/income-breakdown`,
  CURRENT_ACCOUNT: `${API_URL}/current-account`,
  CURRENT_ACCOUNT_CLIENT: `${API_URL}/current-account/client/:clientId`,
  CURRENT_ACCOUNT_PAYMENT: `${API_URL}/current-account/client/:clientId/payment`,
  CURRENT_ACCOUNT_SUMMARY: `${API_URL}/current-account/summary`,
  ENTRIES: `${API_URL}/entries`,
  ENTRIES_BY_CLIENT: (clientId) => `${API_URL}/entries/clients/${clientId}`,
  ENTRIES_REGISTER: (clientId) => `${API_URL}/entries/clients/${clientId}/register`,
  PRODUCTS: `${API_URL}/products`,
  PRODUCTS_ALERTS: `${API_URL}/products/alerts`,
  PRODUCT_BY_ID: (id) => `${API_URL}/products/${id}`,
  PRODUCT_MOVEMENTS: (productId) => `${API_URL}/products/${productId}/movements`,
  PRODUCT_MOVEMENTS_ALL: `${API_URL}/products/movements/all`,
  PRODUCT_MOVEMENTS_CREATE: `${API_URL}/products/movements`,
  CATEGORIES: `${API_URL}/categories`,
  CATEGORY_BY_ID: (id) => `${API_URL}/categories/${id}`,
  SALES: `${API_URL}/sales`,
  SALE_BY_ID: (id) => `${API_URL}/sales/${id}`,
  REPORTS_MEMBERSHIPS: `${API_URL}/reports/memberships`,
  REPORTS_SALES: `${API_URL}/reports/sales`,
}

export default API_URL
